version: "{build}"

branches:
  only:
    - mb-publish-artifacts-from-appveyor

skip_tags: true
clone_folder: c:\projects\atom
clone_depth: 10

environment:
  ATOM_DEV_RESOURCE_PATH: c:\projects\atom

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node 4.2.1

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\projects\atom\script\build.cmd
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%

test: off
deploy: off
